#!/usr/bin/env python3
"""
generate_readme.py
Automatically generates README.md for the Square utilities project.

It scans:
- extractors/
- parsers/
- tipout/
- main entrypoints

Then writes README.md with a clean structure.

Run with:
    uv run generate_readme.py
"""

import os
from pathlib import Path

ROOT = Path(__file__).parent.resolve()

# ----------------------------
# Helpers
# ----------------------------

def list_python_modules(path, exclude=None):
    """List .py files in a folder, excluding __init__ and exclusions."""
    if exclude is None:
        exclude = []
    modules = []
    if not path.exists():
        return modules
    for file in sorted(path.glob("*.py")):
        if file.name.startswith("__") or file.stem in exclude:
            continue
        modules.append(file.stem)
    return modules


def generate_tree(path, prefix=""):
    """Generate an ASCII tree of the repository."""
    items = sorted([p for p in path.iterdir() if not p.name.startswith(".")])
    lines = []
    for idx, item in enumerate(items):
        connector = "└── " if idx == len(items) - 1 else "├── "
        lines.append(prefix + connector + item.name)
        if item.is_dir():
            extension = "    " if idx == len(items) - 1 else "│   "
            lines.extend(generate_tree(item, prefix + extension))
    return lines


# ----------------------------
# Assemble content
# ----------------------------

def build_readme():
    extractors = list_python_modules(ROOT / "extractors", exclude=["base"])
    parsers = list_python_modules(ROOT / "parsers")
    tipout_modules = list_python_modules(ROOT / "tipout", exclude=["tipout_main"])
    project_tree = "\n".join(generate_tree(ROOT))

    readme = f"""
# Square Data Utilities
Automatically generated README for The Curd Nerd / The Wedge Square data tools.

This repository contains two main entrypoints:

- `square_order_info.py` (order extraction)
- `tipout/tipout_main.py` (multi-location payroll + tipout)

Below is project information generated automatically from the repository layout.

---

## Extractors

These modules handle all board-type order extraction:

{''.join(f'- {name}\n' for name in extractors)}

---

## Parsers

These modules clean and normalize Square order fields:

{''.join(f'- {name}\n' for name in parsers)}

---

## Tipout System Modules

These modules handle timecard extraction, payments, aggregation, distribution, and reporting:

{''.join(f'- {name}\n' for name in tipout_modules)}

Main entrypoint:

- tipout_main

---

## Project Structure

---
{project_tree}

## Environment Variables

The scripts require:

export SQUARE_ACCESS_TOKEN="your-token"
export SQUARE_LOCATION_ID="optional default location"


If multiple locations exist, the tipout script automatically detects and processes them.

---

## Usage

### Order Extraction

uv run square_order_info.py --item "cheese board" --start 2025-11-01 --end 2025-11-30


Outputs JSON + Excel files.

### Weekly Payroll Tipout

uv run tipout/tipout_main.py

Optional:

uv run tipout/tipout_main.py --date 2025-02-02
uv run tipout/tipout_main.py --ignore 2025-02-15 2025-02-16


---

## Adding New Extractors

Add a new file to `extractors/`, subclass `BaseExtractor`, and define `KEYWORD`.
The system will automatically detect it on next README generation.

---

## Auto-Generated README

This README was generated by `generate_readme.py`.
To regenerate:

uv run generate_readme.py
"""

    return readme


# ----------------------------
# Main entrypoint
# ----------------------------

def main():
    readme_path = ROOT / "README.md"
    readme = build_readme()
    readme_path.write_text(readme, encoding="utf-8")
    print(f"README.md generated at: {readme_path}")


if __name__ == "__main__":
    main()